### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
## What changed?

- I moved files around
- I created a proper python package
- I removed the controllers and simulation files (moved to dg_demos)
- I renamed the quadruped files to "solo" instead of "quadruped" => this impied to use a deprecated policy of cmake. We should rename those with another name: solo8?

## CI:

- still difficult to test if things works properly as it is robot specific or simulations.
    - With @vincentberenz we want to make a tv screen in place where all the simu would continously run and create some report from these simulations...
    - Another thing would be to check the simulation in bamboo and check if the robot goes wild: base pose is at the moon.

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
If you are ok with this PR, I still need to remove the python/dg_blmc_robots/deprecated folder

**Comment by jviereck** [comment]
Hi Max,

for these kinds of file moves, the `dg_quadruped_calib2zero.py ` is not a controller to me but more a demo / setting things up to run on the real robot:

```
 dg_blmc_robots/python/ -> dg_blmc_robots/deprecated/dg_demos/solo/controllers/dg_quadruped_calib2zero.py 
```

> With @vincentberenz we want to make a tv screen in place where all the simu would continously run and create some report from these simulations...

This requires manual checking, which, is possible, I think we should try to avoid.

> Another thing would be to check the simulation in bamboo and check if the robot goes wild: base pose is at the moon.

Yes. We should run the demos using the bullet simulation setup we have and write standard python unit tests to verify the robot ends up in a desired end posture.

**Comment by MaximilienNaveau** [comment]
Ok, but you did not say anything about the actual files in this repos...
All in the deprecated are moved to dg_demos and will be deleted.
For the semantic problem we can see a bit later I would like to land this PR.

**Comment by MaximilienNaveau** [comment]
Removed the deprecated files and fix the build propblems

**Pull request merged**
